# GitHub Sponsors funding options

# Preferred funding platforms
github: [Kandil7]

# Alternative platforms
# patreon: username
# open_collective: project-name
# ko_fi: username
# tidelift: npm/prprompts-flutter-generator
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://paypal.me/username', 'https://buymeacoffee.com/username']
