blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Kandil7/prprompts-flutter-generator/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/Kandil7/prprompts-flutter-generator/blob/master/README.md
    about: Read the full documentation
  - name: 🔧 Troubleshooting Guide
    url: https://github.com/Kandil7/prprompts-flutter-generator/blob/master/docs/TROUBLESHOOTING.md
    about: Find solutions to common problems
  - name: 📖 Best Practices
    url: https://github.com/Kandil7/prprompts-flutter-generator/blob/master/docs/BEST-PRACTICES.md
    about: Learn how to use PRPROMPTS effectively
