name: Feature Request
description: Suggest a new feature or enhancement for PRPROMPTS
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your ideas for making PRPROMPTS better.

        Before submitting, please:
        - Check the [roadmap](https://github.com/Kandil7/prprompts-flutter-generator/issues?q=is%3Aissue+is%3Aopen+label%3Aroadmap) to see if it's already planned
        - Search [existing feature requests](https://github.com/Kandil7/prprompts-flutter-generator/issues?q=is%3Aissue+label%3Aenhancement) to avoid duplicates

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm frustrated when I have to manually configure GDPR compliance for every project...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: |
        Add GDPR as a compliance option in the PRD wizard, with automatic generation of:
        - Data export functionality
        - Data deletion (right to be forgotten)
        - Consent management
        - Cookie tracking controls
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used.
      placeholder: |
        European healthcare apps need both HIPAA and GDPR compliance.
        This would allow developers to select both standards in the wizard
        and get PRPROMPTS that cover all requirements.
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Expands PRPROMPTS to European market
        - Saves developers 10-15 hours per project
        - Reduces compliance implementation errors
        - Provides tested patterns for GDPR
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        - Manual implementation (current workaround, takes 10+ hours)
        - Third-party GDPR libraries (doesn't integrate with PRPROMPTS patterns)
        - Custom PRPROMPTS (requires deep GDPR knowledge)
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall under?
      options:
        - CLI Command
        - PRD Wizard
        - PRPROMPTS Generation
        - Automation Command
        - Compliance Standard
        - AI Platform Support
        - Documentation
        - Testing
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve workflow
        - High - Blocking current project
        - Critical - Required for production use
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this feature?
      options:
        - All users
        - Healthcare developers
        - E-commerce developers
        - Education developers
        - Enterprise developers
        - Individual developers
        - Specific industry (please specify below)
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Suggestions (Optional)
      description: If you have ideas on how to implement this, share them here.
      placeholder: |
        1. Add GDPR option to src/cli/create.js compliance choices
        2. Create new PRPROMPTS:
           - gdpr-data-export.md
           - gdpr-data-deletion.md
           - gdpr-consent-management.md
        3. Add example in examples/gdpr-app-example.md
        4. Update README with GDPR documentation
      render: markdown
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Code Examples (Optional)
      description: Provide code examples if applicable.
      placeholder: |
        ```dart
        class GdprDataExportService {
          Future<UserDataExport> exportUserData(String userId) async {
            // Export all user data in machine-readable format
          }
        }
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references.
      placeholder: |
        - GDPR official documentation: https://gdpr.eu/
        - Similar implementation in [other tool]
        - Screenshots of desired UI/workflow
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to this feature?
      options:
        - label: I would like to implement this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false
        - label: I can provide example code or use cases
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched for [existing feature requests](https://github.com/Kandil7/prprompts-flutter-generator/issues?q=is%3Aissue+label%3Aenhancement)
          required: true
        - label: I have checked the [roadmap](https://github.com/Kandil7/prprompts-flutter-generator/issues?q=is%3Aissue+is%3Aopen+label%3Aroadmap)
          required: true
        - label: This feature aligns with PRPROMPTS' goals (Flutter development, Clean Architecture, security-first)
          required: true
        - label: I have provided a clear use case and benefits
          required: true
