# Claude Code Commands Configuration for PRPROMPTS Generator
# Version: 2.2.0

commands:
  # PRD Creation Commands
  create-prd:
    prompt: "prompts/generate-prd.md"
    description: "Interactive PRD creation wizard (10 questions)"

  auto-gen-prd:
    prompt: "prompts/auto-generate-prd.md"
    description: "Auto-generate PRD from description (zero interaction)"

  prd-from-files:
    prompt: "prompts/generate-prd-from-files.md"
    description: "Generate PRD from existing markdown files (optional input)"

  # PRD Analysis
  analyze-prd:
    prompt: "prompts/analyze-prd.md"
    description: "Validate and analyze PRD, show customizations"

  # PRPROMPTS Generation Commands
  gen-prprompts:
    prompt: "prompts/prprompts-generator.md"
    description: "Generate all 32 PRPROMPTS files from PRD"

  gen-phase-1:
    prompt: "prompts/phase-1-core.md"
    description: "Generate Phase 1: Core Architecture (10 files)"

  gen-phase-2:
    prompt: "prompts/phase-2-quality.md"
    description: "Generate Phase 2: Quality & Security (12 files)"

  gen-phase-3:
    prompt: "prompts/phase-3-demo.md"
    description: "Generate Phase 3: Demo & Learning (10 files)"

  gen-file:
    prompt: "prompts/single-file-generator.md"
    description: "Generate a single PRPROMPTS file by name"

# Project Settings
project:
  name: "PRPROMPTS Flutter Generator"
  version: "2.2.0"
  description: "Generate customized development guides from PRD"

# Default Behaviors
defaults:
  auto_approve: false
  verbose: true
  save_context: true
